
spring:
  datasource:
    password:Peleweb@12
    url:jdbc:mysql://localhost:3306/peleweb
    username:root
  jpa:
    hibernate:
      ddl-auto:create
    properties:
      hibernate:
        dialect: org.hibernate.dailect.MySQL8Dialect
        format_sql: true
  show-sql: true
